### ISSUE TITLE
Typo in server.js

### ISSUE THREAD

**Issue by aamay001** [Thinkful-Ed/blog-app-mongoose-challenge-solution#6]
Line 104 in server.js has req.params.ID.

The 'ID' after params should be lowercase.

**Comment by tsongas** [comment]
Submitted PRs that fix this in master https://github.com/Thinkful-Ed/blog-app-mongoose-challenge-solution/pull/15 and feature/tests https://github.com/Thinkful-Ed/blog-app-mongoose-challenge-solution/pull/16.

**Comment by aamay001** [comment]
Thanks!
